
quarkus.http.auth.permission.all-resources.paths=/*
quarkus.http.auth.permission.all-resources.policy=authenticated

quarkus.oidc.application-type=web-app
quarkus.oidc.logout.path=/logout
quarkus.oidc.auth-server-url=http://localhost:7777/realms/car-rental
quarkus.oidc.client-id=users-service
quarkus.oidc.token-state-manager.split-tokens=true
