quarkus.http.port=8083

quarkus.datasource.db-kind=postgresql
quarkus.datasource.username=inventory_service
quarkus.datasource.password=inventory_password
quarkus.datasource.jdbc.url=jdbc:postgresql://localhost:5432/inventory_db

quarkus.hibernate-orm.database.generation=drop-and-create
